{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.postgres.name }}
  labels:
    {{- include "langtrace.labels" . | nindent 4 }}
spec:
  selector:
    app:  {{ .Values.postgres.name }}
  ports:
    - protocol: TCP
      port: 5432
      targetPort: {{ .Values.postgres.containerPort }}
{{- end}}
