apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.langtraceApp.name }}-svc
  labels:
    {{- include "langtrace.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Values.langtraceApp.name }}-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
